# Generated by Django 3.1.7 on 2021-03-07 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='num_number',
            new_name='num_member',
        ),
    ]
