# Generated by Django 3.1.7 on 2021-03-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20210308_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='num_member',
            new_name='num_number',
        ),
    ]
